const GET_MOVIES_DATA_REQUEST = "GET_MOVIES_DATA_REQUEST";
const GET_MOVIES_DATA_SUCCUSS = "GET_MOVIES_DATA_SUCCUSS";
const GET_MOVIES_DATA_FAILURE = "GET_MOVIES_DATA_FAILURE";

export {
  GET_MOVIES_DATA_REQUEST,
  GET_MOVIES_DATA_SUCCUSS,
  GET_MOVIES_DATA_FAILURE,
};
